version: "3"
services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "8080:80"
        volumes:
            - ./src:/app