name: pr_opened     # Run CI or build docker images (if any)
on:
    pull_request:
        branches: [develop, staging, master]
        # Note: By default, a workflow only runs when a `pull_request`'s activity type is opened, synchronize, or reopened.
        # To trigger workflows for more activity types, use the `types` keyword.
        types: [opened, synchronize, reopened]

jobs:
    docker:
        name: Build & Push docker
        runs-on: ubuntu-20.04
        steps:
        # -   name: Configure AWS credentials
        #     uses: aws-actions/configure-aws-credentials@v1
        #     with:
        #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #         aws-region: ap-southeast-1

        # -   name: Login ECR
        #     id: login-ecr
        #     uses: aws-actions/amazon-ecr-login@v1

        -   name: Checkout source
            uses: actions/checkout@v2

        -   name: Build Docker Images
            id: docker-build
            env:
                ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                IMAGE_TAG: ${{ github.sha }}
            run: |
                docker-compose build nginx \
                docker tag nginx:latest ${ECR_REGISTRY}/nginx:${IMAGE_TAG}